#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# add crontab job
if [[ -z ${CRON} ]]; then
    echo "0 20 * * * /usr/local/bin/python3 /app/base.py" >> /etc/crontabs/root
else
    echo "${CRON} /usr/local/bin/python3 /app/base.py" >> /etc/crontabs/root
fi

# set permissions and import user crontabs
chown root:root /etc/crontabs/root
chmod 600 /etc/crontabs/root

# run scheduler
crond -f